<Project>
  <PropertyGroup>
    <Version>2026.10.10.0926</Version>
    <AssemblyVersion>2026.10.10.0926</AssemblyVersion>
    <FileVersion>2026.10.10.0926</FileVersion>
    <InformationalVersion>2026.10.10.0926</InformationalVersion>
    <ProductVersion>2026.10.10.0926</ProductVersion>
  </PropertyGroup>
</Project>
